paths:
  scrape_root: "/Users/prabhatkumar.singh/Downloads/conftest/confluence_export_CKB_V2/CKB/RMI Cloud Platform - Platform"
  sqlite_path: "data/rag.db"
  chroma_dir: "data/chroma"

embeddings:
  model: "BAAI/bge-m3"
  dim: 1024
  batch_size: 128
  device: "auto"

chunking:
  max_tokens: 550
  overlap_tokens: 80
  prefer_structure: true

retrieval:
  k_vec: 25
  k_fts: 25
  fusion: "rrf"
  weights:
    semantic: 0.7
    keyword: 0.3

rerank:
  enabled: true
  model: "BAAI/bge-reranker-base"
  top_n: 8

abstain:
  min_rerank_score: 0.25
  min_chunks: 2

llm:
  model: "qwen2.5:7b"
  base_url: "http://localhost:11434"
  temperature: 0.2
  max_tokens: 1100

redaction:
  enabled: true
  patterns:
    - 'api[_-]?key'
    - 'password'
    - 'secret'
    - 'token'
    - 'bearer'
    - 'jwt'